-- ============================================================================
-- Migration: Webhook-based order creation
-- Date:      2026-05-09
-- Purpose:   Enables the architectural fix for the "got money, lost order"
--            class of bugs (3DS interrupts, ad blockers, browser unloads).
--
--            See lib/orders/finalize.ts and the rewritten /api/webhooks/stripe
--            for the application-side changes that depend on this migration.
-- ============================================================================
--
-- WHAT THIS DOES:
-- 1. Adds 'pending' as a valid order status. /api/orders/init creates orders
--    in this status before Stripe charges the card. The webhook (or browser
--    fallback) flips them to 'received' on payment_intent.succeeded.
-- 2. Adds a partial unique index on stripe_payment_intent_id. This guarantees
--    one paid order per PaymentIntent (prevents double-creation if both the
--    webhook and the browser-side fallback fire concurrently).
--
-- IMPORTANT: Run this BEFORE deploying the matching code changes. If you
-- deploy the code first, every checkout will fail because the code inserts
-- with status='pending' which the existing CHECK constraint rejects.
-- ============================================================================


-- 1. Allow 'pending' as a valid order status.
-- The existing constraint name is auto-generated by Postgres (orders_status_check
-- by convention). DROP IF EXISTS is safe — won't error if the name differs.
ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_status_check;

ALTER TABLE orders ADD CONSTRAINT orders_status_check
  CHECK (status IN (
    'pending',         -- order created, awaiting payment confirmation (NEW)
    'received',        -- payment confirmed, order accepted
    'in_production',   -- being manufactured
    'quality_check',   -- post-production inspection
    'shipped',         -- handed to FedEx
    'delivered',       -- arrived at customer
    'cancelled'        -- voided / refunded
  ));


-- 2. Enforce one order per PaymentIntent.
-- Partial index: NULLs are allowed (legacy orders without a PI), but any
-- non-null value must be unique. This is the safety net that prevents the
-- webhook + browser fallback from both creating an order for the same PI.
CREATE UNIQUE INDEX IF NOT EXISTS orders_stripe_pi_unique
  ON orders(stripe_payment_intent_id)
  WHERE stripe_payment_intent_id IS NOT NULL;


-- 3. Verify both changes landed
DO $$
DECLARE
  status_check_exists BOOLEAN;
  pi_index_exists BOOLEAN;
BEGIN
  SELECT EXISTS (
    SELECT 1 FROM information_schema.check_constraints
    WHERE constraint_name = 'orders_status_check'
      AND check_clause LIKE '%pending%'
  ) INTO status_check_exists;

  SELECT EXISTS (
    SELECT 1 FROM pg_indexes
    WHERE tablename = 'orders' AND indexname = 'orders_stripe_pi_unique'
  ) INTO pi_index_exists;

  IF NOT status_check_exists THEN
    RAISE EXCEPTION 'Migration failed: orders_status_check constraint missing or does not include pending';
  END IF;

  IF NOT pi_index_exists THEN
    RAISE EXCEPTION 'Migration failed: orders_stripe_pi_unique index missing';
  END IF;

  RAISE NOTICE 'Migration verified: pending status allowed, stripe_payment_intent_id unique index in place';
END $$;
