// AUTO-GENERATED from WWS Master Fabric List CSV (column K: Color Filter Pill).
// 679 mappings covering 702 fabric SKUs across 9 color groups.
// Do not edit by hand — re-run the build script if the CSV is updated.
//
// Lookup key format: `${slugify(WWS Fabric Name)}_${slugify(Color)}`
// where slugify = lowercase + remove non-alphanumeric. This makes the lookup
// resilient to differences in spacing/punctuation between the codebase's URL-derived
// color names (e.g. 'Pearl | Grey') and the CSV's free-form names (e.g. 'Pearl Grey').

export type ColorPill =
  | 'Whites'
  | 'Beige & Natural Tones'
  | 'Browns & Earth Tones'
  | 'Yellows'
  | 'Reds & Oranges'
  | 'Greens'
  | 'Blues'
  | 'Grays'
  | 'Blacks & Charcoal';

// Display order: light-to-dark visual flow for the 'browse mode' grouped sections.
// Tweak this array to reorder how sections appear in the FabricPicker.
export const COLOR_PILL_ORDER: ColorPill[] = [
  'Whites',
  'Beige & Natural Tones',
  'Browns & Earth Tones',
  'Yellows',
  'Reds & Oranges',
  'Greens',
  'Blues',
  'Grays',
  'Blacks & Charcoal',
];

// Hex swatch shown next to each pill label. Approximate color of the group.
export const COLOR_PILL_DOTS: Record<ColorPill, string> = {
  'Whites': '#f0ece4',
  'Beige & Natural Tones': '#d4b896',
  'Browns & Earth Tones': '#8b6f47',
  'Yellows': '#d4a72c',
  'Reds & Oranges': '#b85c3e',
  'Greens': '#5a7a3e',
  'Blues': '#4a6b8a',
  'Grays': '#7a7a7a',
  'Blacks & Charcoal': '#1a1a1a',
};

export const slugifyForPill = (s: string): string =>
  s.toLowerCase().replace(/[^a-z0-9]/g, '');

export const FABRIC_COLOR_PILLS: Record<string, ColorPill> = {
  'airlitemesh1p_beigebeige': 'Beige & Natural Tones',
  'airlitemesh1p_beigegray': 'Beige & Natural Tones',
  'airlitemesh1p_beigesable': 'Beige & Natural Tones',
  'airlitemesh1p_charcoalbronze': 'Browns & Earth Tones',
  'airlitemesh1p_charcoalcharcoal': 'Blacks & Charcoal',
  'airlitemesh1p_charcoalgray': 'Grays',
  'airlitemesh1p_grayblue': 'Grays',
  'airlitemesh1p_graydarkgray': 'Grays',
  'airlitemesh1p_graygray': 'Grays',
  'airlitemesh1p_whitebeige': 'Beige & Natural Tones',
  'airlitemesh1p_whitegray': 'Grays',
  'airlitemesh1p_whitewhite': 'Whites',
  'armorweave_blackblack': 'Blacks & Charcoal',
  'armorweave_blackwhite': 'Blacks & Charcoal',
  'armorweave_chalkwhite': 'Whites',
  'armorweave_emeryemery': 'Blacks & Charcoal',
  'armorweave_emerywhite': 'Blacks & Charcoal',
  'armorweave_gypsumwhite': 'Beige & Natural Tones',
  'armorweave_pewterpewter': 'Grays',
  'armorweave_pewterwhite': 'Grays',
  'armorweave_whitewhite': 'Whites',
  'blackoutx0p_alabaster': 'Beige & Natural Tones',
  'blackoutx0p_chalk': 'Whites',
  'blackoutx0p_clay': 'Beige & Natural Tones',
  'blackoutx0p_ebony': 'Blacks & Charcoal',
  'blackoutx0p_fleece': 'Beige & Natural Tones',
  'blackoutx0p_flint': 'Blacks & Charcoal',
  'blackoutx0p_grey': 'Grays',
  'blackoutx0p_mink': 'Browns & Earth Tones',
  'blackoutx0p_mocha': 'Browns & Earth Tones',
  'blackoutx0p_pearlgray': 'Beige & Natural Tones',
  'blackoutx0p_sand': 'Beige & Natural Tones',
  'blackoutx0p_taupe': 'Beige & Natural Tones',
  'breezeflex_blanc': 'Beige & Natural Tones',
  'breezeflex_chartreux': 'Beige & Natural Tones',
  'breezeflex_loutre': 'Browns & Earth Tones',
  'breezeflex_mississippi': 'Reds & Oranges',
  'breezeflex_sahel': 'Beige & Natural Tones',
  'breezeguard_cloud': 'Whites',
  'breezeguard_dune': 'Beige & Natural Tones',
  'breezeguard_ice': 'Whites',
  'breezeguard_limestone': 'Grays',
  'breezeguard_midnight': 'Blacks & Charcoal',
  'breezeguard_mist': 'Grays',
  'breezeguard_nimbus': 'Grays',
  'breezeguard_odyssey': 'Grays',
  'breezeguard_orient': 'Blacks & Charcoal',
  'breezeguard_porcelain': 'Beige & Natural Tones',
  'breezeguard_stone': 'Beige & Natural Tones',
  'breezeguard_tundra': 'Grays',
  'clearview10_charcoalbronze': 'Browns & Earth Tones',
  'clearview10_charcoalcharcoal': 'Blacks & Charcoal',
  'clearview10_charcoalgrey': 'Grays',
  'clearview10_pearlgreylinen': 'Grays',
  'clearview10_pearlgreypearlgrey': 'Grays',
  'clearview10_whitelinen': 'Beige & Natural Tones',
  'clearview10_whitepearlgrey': 'Beige & Natural Tones',
  'clearview10_whitewhite': 'Whites',
  'clearview10_wowwhite': 'Whites',
  'clearview1p_charcoal': 'Blacks & Charcoal',
  'clearview1p_charcoalbrown': 'Browns & Earth Tones',
  'clearview1p_charcoalgray': 'Blacks & Charcoal',
  'clearview1p_charcoalslate': 'Blacks & Charcoal',
  'clearview1p_charcoaltoupe': 'Blacks & Charcoal',
  'clearview1p_oyster': 'Whites',
  'clearview1p_oysterbeige': 'Beige & Natural Tones',
  'clearview1p_oystercharcoal': 'Grays',
  'clearview1p_oysterchestnut': 'Browns & Earth Tones',
  'clearview1p_oysterpearlgray': 'Beige & Natural Tones',
  'clearview1p_oysterpewter': 'Grays',
  'coastalluxe5_angora': 'Whites',
  'coastalluxe5_gull': 'Whites',
  'coastalluxe5_horizon': 'Whites',
  'coastalluxe5_ink': 'Blacks & Charcoal',
  'coastalluxe5_iron': 'Grays',
  'coastalluxe5_jasmine': 'Whites',
  'coastalluxe5_lyric': 'Whites',
  'coastalluxe5_melody': 'Whites',
  'coastalluxe5_merino': 'Whites',
  'coastalluxe5_monsoon': 'Grays',
  'coastalluxe5_pearl': 'Whites',
  'coastalluxe5_porpoise': 'Grays',
  'coastalluxe5_quartz': 'Blacks & Charcoal',
  'coastalluxe5_quill': 'Whites',
  'coastalluxe5_steel': 'Blacks & Charcoal',
  'coastalluxe5_summerstorm': 'Grays',
  'dayglow3_acapulco': 'Blues',
  'dayglow3_anthracite': 'Blacks & Charcoal',
  'dayglow3_atlantis': 'Blues',
  'dayglow3_aureolin': 'Yellows',
  'dayglow3_black': 'Blacks & Charcoal',
  'dayglow3_boulder': 'Grays',
  'dayglow3_bronze': 'Blacks & Charcoal',
  'dayglow3_caramel': 'Reds & Oranges',
  'dayglow3_citrus': 'Yellows',
  'dayglow3_cloud': 'Grays',
  'dayglow3_jungle': 'Browns & Earth Tones',
  'dayglow3_limeblossom': 'Beige & Natural Tones',
  'dayglow3_midnightblue': 'Blues',
  'dayglow3_newshea': 'Whites',
  'dayglow3_offwhite': 'Beige & Natural Tones',
  'dayglow3_platinum': 'Grays',
  'dayglow3_red': 'Reds & Oranges',
  'dayglow3_sandybeige': 'Beige & Natural Tones',
  'dayglow3_taupe': 'Beige & Natural Tones',
  'dayglow3_vanilla': 'Beige & Natural Tones',
  'dayglow3_white': 'Whites',
  'daylitemax_almond': 'Beige & Natural Tones',
  'daylitemax_aspen': 'Grays',
  'daylitemax_blanco': 'Whites',
  'daylitemax_dove': 'Whites',
  'daylitemax_fleece': 'Grays',
  'daylitemax_fossil': 'Beige & Natural Tones',
  'daylitemax_raffia': 'Beige & Natural Tones',
  'daylitemax_vine': 'Grays',
  'desertfade_almond': 'Beige & Natural Tones',
  'desertfade_cloud': 'Whites',
  'desertfade_desert': 'Beige & Natural Tones',
  'desertfade_ebony': 'Blacks & Charcoal',
  'desertfade_espresso': 'Browns & Earth Tones',
  'desertfade_linen': 'Whites',
  'desertfade_polar': 'Whites',
  'designmesh6_flagstone': 'Browns & Earth Tones',
  'designmesh6_harvest': 'Browns & Earth Tones',
  'designmesh6_hazelnut': 'Browns & Earth Tones',
  'designmesh6_naturelle': 'Beige & Natural Tones',
  'designmesh6_parchment': 'Beige & Natural Tones',
  'designmesh6_riverrock': 'Beige & Natural Tones',
  'designmesh6_tumbleweed': 'Browns & Earth Tones',
  'earthblock1p_charcoalbronze': 'Blacks & Charcoal',
  'earthblock1p_charcoalcharcoal': 'Blues',
  'earthblock1p_charcoalgrey': 'Blacks & Charcoal',
  'earthblock1p_linenlinen': 'Beige & Natural Tones',
  'earthblock1p_pearlgreylinen': 'Grays',
  'earthblock1p_pearlgreypearlgrey': 'Grays',
  'earthblock1p_whitelinen': 'Beige & Natural Tones',
  'earthblock1p_whitepearlgrey': 'Grays',
  'earthblock1p_whitewhite': 'Whites',
  'ecoshield1p_p12oyster': 'Whites',
  'ecoshield1p_p13oysterbeige': 'Beige & Natural Tones',
  'ecoshield1p_p14oysterpearlgray': 'Grays',
  'ecoshield1p_p84britewhite': 'Whites',
  'ecoshield1p_q20beige': 'Beige & Natural Tones',
  'ecoshield1p_q21beigepearlgray': 'Beige & Natural Tones',
  'ecoshield1p_v20pearlgray': 'Beige & Natural Tones',
  'ecoshield1p_v21charcoal': 'Blacks & Charcoal',
  'ecoshield1p_v22charcoalgray': 'Blacks & Charcoal',
  'ecoshield1p_v24charcoalchestnut': 'Browns & Earth Tones',
  'ecoshield1p_v32charcoalalpaca': 'Browns & Earth Tones',
  'ecotherm_cotton': 'Whites',
  'ecotherm_flint': 'Blacks & Charcoal',
  'ecotherm_parchment': 'Beige & Natural Tones',
  'ecotherm_pebble': 'Grays',
  'ecotherm_seagrass': 'Grays',
  'ecotherm_sesame': 'Beige & Natural Tones',
  'ecotherm_shale': 'Grays',
  'ecotherm_spice': 'Grays',
  'ecoview10p_charcoalbronze': 'Blacks & Charcoal',
  'ecoview10p_charcoalcharcoal': 'Blues',
  'ecoview10p_charcoalgrey': 'Blacks & Charcoal',
  'ecoview10p_whitelinen': 'Beige & Natural Tones',
  'ecoview10p_whitepearlgrey': 'Grays',
  'ecoview10p_whitewhite': 'Whites',
  'ecoweave3p_aspen': 'Beige & Natural Tones',
  'ecoweave3p_cedar': 'Browns & Earth Tones',
  'ecoweave3p_charcoalapricot': 'Browns & Earth Tones',
  'ecoweave3p_charcoalcharcoal': 'Blacks & Charcoal',
  'ecoweave3p_charcoalcocoa': 'Browns & Earth Tones',
  'ecoweave3p_charcoalgrey': 'Blacks & Charcoal',
  'ecoweave3p_charcoalgreystone': 'Blacks & Charcoal',
  'ecoweave3p_cypress': 'Beige & Natural Tones',
  'ecoweave3p_elm': 'Beige & Natural Tones',
  'ecoweave3p_hickory': 'Reds & Oranges',
  'ecoweave3p_magnolia': 'Beige & Natural Tones',
  'ecoweave3p_maple': 'Browns & Earth Tones',
  'ecoweave3p_oak': 'Browns & Earth Tones',
  'ecoweave3p_palmetto': 'Browns & Earth Tones',
  'ecoweave3p_pearlgrey': 'Grays',
  'ecoweave3p_pearllinen': 'Beige & Natural Tones',
  'ecoweave3p_pearlpearl': 'Grays',
  'ecoweave3p_poplar': 'Beige & Natural Tones',
  'ecoweave3p_sycamore': 'Browns & Earth Tones',
  'ecoweave3p_whitelinen': 'Whites',
  'ecoweave3p_whitepearl': 'Whites',
  'ecoweave3p_whitewhite': 'Whites',
  'ecoweave3p_willow': 'Beige & Natural Tones',
  'feathermesh_blanc': 'Whites',
  'feathermesh_chartreux': 'Grays',
  'feathermesh_loutre': 'Browns & Earth Tones',
  'feathermesh_mississippi': 'Beige & Natural Tones',
  'feathermesh_sahel': 'Beige & Natural Tones',
  'greenshade5p_charcoalbronze': 'Blacks & Charcoal',
  'greenshade5p_charcoalcharcoal': 'Blacks & Charcoal',
  'greenshade5p_charcoalpearlgrey': 'Grays',
  'greenshade5p_pearlgreylinen': 'Beige & Natural Tones',
  'greenshade5p_pearlgreypearlgrey': 'Grays',
  'greenshade5p_whitelinen': 'Beige & Natural Tones',
  'greenshade5p_whitepearlgrey': 'Grays',
  'greenshade5p_whitewhite': 'Whites',
  'infinityveil3p_almond': 'Beige & Natural Tones',
  'infinityveil3p_bark': 'Blacks & Charcoal',
  'infinityveil3p_barley': 'Beige & Natural Tones',
  'infinityveil3p_cotton': 'Whites',
  'infinityveil3p_midnight': 'Blacks & Charcoal',
  'infinityveil3p_nickel': 'Grays',
  'infinityveil3p_slate': 'Blacks & Charcoal',
  'infinityveil3p_stone': 'Grays',
  'infinityveil3p_wheat': 'Beige & Natural Tones',
  'loopmesh3p_alloy': 'Grays',
  'loopmesh3p_cream': 'Whites',
  'loopmesh3p_oatmeal': 'Grays',
  'loopmesh3p_opticalwhite': 'Whites',
  'loopmesh3p_oxygen': 'Grays',
  'loopmesh3p_silver': 'Whites',
  'loopmesh3p_steelgrey': 'Blacks & Charcoal',
  'loopmesh3p_white': 'Whites',
  'lumiscreen3_charcoalbronze': 'Blacks & Charcoal',
  'lumiscreen3_charcoalcharcoal': 'Blacks & Charcoal',
  'lumiscreen3_charcoalgrey': 'Blacks & Charcoal',
  'lumiscreen3_pearlgreylinen': 'Grays',
  'lumiscreen3_pearlgreypearlgrey': 'Grays',
  'lumiscreen3_whitelinen': 'Beige & Natural Tones',
  'lumiscreen3_whitepearlgrey': 'Whites',
  'lumiscreen3_whitewhite': 'Whites',
  'luxetone_basalt': 'Browns & Earth Tones',
  'luxetone_limestone': 'Beige & Natural Tones',
  'luxetone_obsidian': 'Blacks & Charcoal',
  'luxetone_pumice': 'Beige & Natural Tones',
  'luxetone_quartz': 'Whites',
  'luxetone_slate': 'Beige & Natural Tones',
  'luxeverona5p_bluegray': 'Grays',
  'luxeverona5p_lakeblue': 'Blues',
  'luxeverona5p_lightblue': 'Grays',
  'luxeverona5p_lightgray': 'Beige & Natural Tones',
  'luxeverona5p_natural': 'Beige & Natural Tones',
  'luxeverona5p_navyblue': 'Blues',
  'luxeverona5p_noir': 'Blacks & Charcoal',
  'luxeverona5p_sand': 'Beige & Natural Tones',
  'luxeverona5p_shadow': 'Reds & Oranges',
  'luxeverona5p_stone': 'Beige & Natural Tones',
  'luxeverona5p_teal': 'Blues',
  'luxeverona5p_vanilla': 'Whites',
  'luxeverona5p_white': 'Whites',
  'microview4_charcoalapricot': 'Browns & Earth Tones',
  'microview4_charcoalcharcoal': 'Blacks & Charcoal',
  'microview4_charcoalcocoa': 'Blacks & Charcoal',
  'microview4_charcoalgrey': 'Blacks & Charcoal',
  'microview4_charcoalsable': 'Blacks & Charcoal',
  'microview4_linensablecocoa': 'Beige & Natural Tones',
  'microview4_linenstone': 'Beige & Natural Tones',
  'microview4_pearllinen': 'Grays',
  'microview4_pearlpearl': 'Grays',
  'microview4_whitelinen': 'Whites',
  'microview4_whitepearl': 'Grays',
  'microview4_whitestone': 'Whites',
  'microview4_whitewhite': 'Whites',
  'naturescreen3p_charcoalbronze': 'Blacks & Charcoal',
  'naturescreen3p_charcoalcharcoal': 'Blues',
  'naturescreen3p_charcoalgrey': 'Blacks & Charcoal',
  'naturescreen3p_whitelinen': 'Beige & Natural Tones',
  'naturescreen3p_whitepearlgrey': 'Grays',
  'naturescreen3p_whitewhite': 'Whites',
  'nightshade_alloy': 'Whites',
  'nightshade_barley': 'Beige & Natural Tones',
  'nightshade_black': 'Blacks & Charcoal',
  'nightshade_graphite': 'Blacks & Charcoal',
  'nightshade_ice': 'Whites',
  'nightshade_pumice': 'Beige & Natural Tones',
  'nightshade_shale': 'Grays',
  'privacylite3p_beige': 'Beige & Natural Tones',
  'privacylite3p_beigepearlgray': 'Beige & Natural Tones',
  'privacylite3p_charcoal': 'Blacks & Charcoal',
  'privacylite3p_charcoalalpaca': 'Browns & Earth Tones',
  'privacylite3p_charcoalchestnut': 'Browns & Earth Tones',
  'privacylite3p_charcoalgrey': 'Blacks & Charcoal',
  'privacylite3p_osterpearlgray': 'Grays',
  'privacylite3p_oyster': 'Whites',
  'privacylite3p_oysterbeige': 'Beige & Natural Tones',
  'privacylite3p_pearlgray': 'Beige & Natural Tones',
  'privacylite3p_white': 'Whites',
  'pureshade5p_alloy': 'Grays',
  'pureshade5p_ash': 'Grays',
  'pureshade5p_barley': 'Whites',
  'pureshade5p_black': 'Blacks & Charcoal',
  'pureshade5p_canyon': 'Grays',
  'pureshade5p_graphite': 'Blacks & Charcoal',
  'pureshade5p_purewhite': 'Whites',
  'pureshade5p_raven': 'Blacks & Charcoal',
  'renewweave3p_blackblack': 'Blacks & Charcoal',
  'renewweave3p_blackblue': 'Blacks & Charcoal',
  'renewweave3p_blackcoffee': 'Blacks & Charcoal',
  'renewweave3p_blackgray': 'Blacks & Charcoal',
  'renewweave3p_blacksmoke': 'Blacks & Charcoal',
  'renewweave3p_graygray': 'Grays',
  'renewweave3p_smokesmoke': 'Beige & Natural Tones',
  'renewweave3p_whitebeige': 'Beige & Natural Tones',
  'renewweave3p_whitegray': 'Grays',
  'renewweave3p_whitesmoke': 'Beige & Natural Tones',
  'renewweave3p_whitewhite': 'Whites',
  'sheerguard5p_beige': 'Beige & Natural Tones',
  'sheerguard5p_beigepearlgray': 'Beige & Natural Tones',
  'sheerguard5p_charcoal': 'Blacks & Charcoal',
  'sheerguard5p_charcoalalpaca': 'Browns & Earth Tones',
  'sheerguard5p_charcoalchestnut': 'Browns & Earth Tones',
  'sheerguard5p_charcoalgrey': 'Blacks & Charcoal',
  'sheerguard5p_osterpearlgray': 'Grays',
  'sheerguard5p_oyster': 'Whites',
  'sheerguard5p_oysterbeige': 'Beige & Natural Tones',
  'sheerguard5p_pearlgray': 'Beige & Natural Tones',
  'sheerguard5p_white': 'Whites',
  'silenthaven_baltic': 'Blues',
  'silenthaven_ceramic': 'Grays',
  'silenthaven_fossil': 'Blacks & Charcoal',
  'silenthaven_lava': 'Blacks & Charcoal',
  'silenthaven_limestone': 'Whites',
  'silenthaven_marble': 'Whites',
  'silenthaven_mineral': 'Whites',
  'silenthaven_plaster': 'Whites',
  'silenthaven_slate': 'Grays',
  'silenthaven_suede': 'Grays',
  'silenthaven_truffle': 'Grays',
  'silklight_barley': 'Beige & Natural Tones',
  'silklight_buckwheat': 'Browns & Earth Tones',
  'silklight_oat': 'Whites',
  'silklight_poppyseed': 'Beige & Natural Tones',
  'silklight_pumpernickel': 'Browns & Earth Tones',
  'silklight_rye': 'Browns & Earth Tones',
  'skyshade1p_bamboobirch': 'Whites',
  'skyshade1p_bamboowheat': 'Beige & Natural Tones',
  'skyshade1p_barkantique': 'Whites',
  'skyshade1p_barkash': 'Beige & Natural Tones',
  'skyshade1p_barkeggshell': 'Whites',
  'skyshade1p_barkpewter': 'Beige & Natural Tones',
  'skyshade1p_barksienna': 'Reds & Oranges',
  'skyshade1p_barksterling': 'Whites',
  'skyshade1p_barktigeroak': 'Reds & Oranges',
  'skyshade1p_blisscotton': 'Whites',
  'skyshade1p_blissfrost': 'Whites',
  'skyshade1p_blissnatural': 'Whites',
  'skyshade1p_blissshadow': 'Blacks & Charcoal',
  'skyshade1p_chenilledriftwood': 'Browns & Earth Tones',
  'skyshade1p_chenillehoney': 'Beige & Natural Tones',
  'skyshade1p_chenillemarshmallow': 'Beige & Natural Tones',
  'skyshade1p_featherclear': 'Whites',
  'skyshade1p_jutecoffee': 'Beige & Natural Tones',
  'skyshade1p_jutefog': 'Grays',
  'skyshade1p_jutelatte': 'Beige & Natural Tones',
  'skyshade1p_juteparchment': 'Beige & Natural Tones',
  'skyshade1p_jutesmoke': 'Grays',
  'skyshade1p_linencinnamon': 'Reds & Oranges',
  'skyshade1p_linenclay': 'Beige & Natural Tones',
  'skyshade1p_linencream': 'Beige & Natural Tones',
  'skyshade1p_linenpearl': 'Beige & Natural Tones',
  'skyshade1p_linentaupe': 'Beige & Natural Tones',
  'skyshade1p_marblesand': 'Beige & Natural Tones',
  'skyshade1p_metroplatinum': 'Beige & Natural Tones',
  'skyshade1p_seaglasschardonnay': 'Beige & Natural Tones',
  'skyshade1p_seaglasscrystal': 'Beige & Natural Tones',
  'skyshade1p_seaglasssilver': 'Grays',
  'skyshade1p_tweedbuckeye': 'Yellows',
  'skyshade1p_tweedglacier': 'Grays',
  'skyshade1p_tweedoatmeal': 'Beige & Natural Tones',
  'skyshade1p_tweedputty': 'Beige & Natural Tones',
  'skyshade1p_tweedsatin': 'Grays',
  'softweave3_agategrey': 'Grays',
  'softweave3_biscuit': 'Beige & Natural Tones',
  'softweave3_carrara': 'Grays',
  'softweave3_celestial': 'Grays',
  'softweave3_charcoal': 'Blacks & Charcoal',
  'softweave3_citrine': 'Browns & Earth Tones',
  'softweave3_cobalt': 'Blacks & Charcoal',
  'softweave3_coffeebean': 'Blacks & Charcoal',
  'softweave3_elephant': 'Grays',
  'softweave3_flint': 'Grays',
  'softweave3_flowerbud': 'Grays',
  'softweave3_glacier': 'Grays',
  'softweave3_jasmine': 'Whites',
  'softweave3_mahogany': 'Blacks & Charcoal',
  'softweave3_maple': 'Beige & Natural Tones',
  'softweave3_mocha': 'Blacks & Charcoal',
  'softweave3_motherofpearl': 'Whites',
  'softweave3_opaline': 'Grays',
  'softweave3_pacific': 'Blues',
  'softweave3_raffia': 'Beige & Natural Tones',
  'softweave3_reed': 'Beige & Natural Tones',
  'softweave3_rope': 'Grays',
  'softweave3_shore': 'Grays',
  'softweave3_tannin': 'Blacks & Charcoal',
  'softweave3_tornado': 'Blacks & Charcoal',
  'softweave3_turmeric': 'Beige & Natural Tones',
  'softweave3_twilight': 'Blacks & Charcoal',
  'softweave3_wheat': 'Beige & Natural Tones',
  'solararmor3_alabaster': 'Beige & Natural Tones',
  'solararmor3_ash': 'Blacks & Charcoal',
  'solararmor3_chalk': 'Whites',
  'solararmor3_ebony': 'Blacks & Charcoal',
  'solararmor3_granite': 'Grays',
  'solararmor3_greystone': 'Beige & Natural Tones',
  'solararmor3_pebblestone': 'Beige & Natural Tones',
  'solararmor3_pewter': 'Beige & Natural Tones',
  'solararmor3_tobacco': 'Blacks & Charcoal',
  'solarblock1_charcoalbronze': 'Blacks & Charcoal',
  'solarblock1_charcoalcharcoal': 'Blacks & Charcoal',
  'solarblock1_charcoalgrey': 'Blacks & Charcoal',
  'solarblock1_pearlgreylinen': 'Grays',
  'solarblock1_pearlgreypearlgrey': 'Grays',
  'solarblock1_whitelinen': 'Whites',
  'solarblock1_whitepearlgrey': 'Grays',
  'solarblock1_whitewhite': 'Whites',
  'solarblock1_wowwhite': 'Whites',
  'solarlite4p_alualu': 'Grays',
  'solarlite4p_aluanthracite': 'Grays',
  'solarlite4p_aluoat': 'Grays',
  'solarlite4p_aluwhite': 'Grays',
  'solarlite4p_aniseed': 'Greens',
  'solarlite4p_anthracite': 'Blacks & Charcoal',
  'solarlite4p_beatenmetal': 'Grays',
  'solarlite4p_boulder': 'Grays',
  'solarlite4p_brick': 'Reds & Oranges',
  'solarlite4p_bronze': 'Browns & Earth Tones',
  'solarlite4p_buttercup': 'Yellows',
  'solarlite4p_champagne': 'Beige & Natural Tones',
  'solarlite4p_concrete': 'Grays',
  'solarlite4p_deepblack': 'Blacks & Charcoal',
  'solarlite4p_deepblue': 'Blues',
  'solarlite4p_deepred': 'Reds & Oranges',
  'solarlite4p_mossgreen': 'Greens',
  'solarlite4p_orange': 'Reds & Oranges',
  'solarlite4p_pepper': 'Yellows',
  'solarlite4p_red': 'Reds & Oranges',
  'solarlite4p_sandybeige': 'Beige & Natural Tones',
  'solarlite4p_snowwhite': 'Whites',
  'solarlite4p_white': 'Whites',
  'solarsoft3_cork': 'Beige & Natural Tones',
  'solarsoft3_ginger': 'Reds & Oranges',
  'solarsoft3_granite': 'Beige & Natural Tones',
  'solarsoft3_jute': 'Beige & Natural Tones',
  'solarsoft3_marble': 'Beige & Natural Tones',
  'solarsoft3_nougat': 'Reds & Oranges',
  'solarsoft3_papyrus': 'Reds & Oranges',
  'solarsoft3_peppercorn': 'Beige & Natural Tones',
  'solarsoft3_porcelain': 'Beige & Natural Tones',
  'solarsoft3_seasalt': 'Beige & Natural Tones',
  'stoneview_black': 'Blacks & Charcoal',
  'stoneview_blackfacade': 'Blacks & Charcoal',
  'stoneview_dovewhite': 'Whites',
  'stoneview_dune': 'Beige & Natural Tones',
  'stoneview_icegray': 'Whites',
  'stoneview_mist': 'Grays',
  'stoneview_moonstone': 'Whites',
  'stoneview_nougat': 'Beige & Natural Tones',
  'stoneview_pearl': 'Whites',
  'stoneview_quill': 'Beige & Natural Tones',
  'stoneview_seal': 'Beige & Natural Tones',
  'stoneview_slate': 'Blacks & Charcoal',
  'stoneview_slatefaade': 'Grays',
  'stoneview_storm': 'Blacks & Charcoal',
  'stoneview_stormfacade': 'Blacks & Charcoal',
  'stoneview_tuxedofaade': 'Grays',
  'stoneview_white': 'Whites',
  'thermaview5_chestnut': 'Grays',
  'thermaview5_coal': 'Grays',
  'thermaview5_granite': 'Grays',
  'thermaview5_linen': 'Beige & Natural Tones',
  'thermoshield1_cappuccino': 'Beige & Natural Tones',
  'thermoshield1_charcoalcharcoaliron': 'Blacks & Charcoal',
  'thermoshield1_charcoalcharcoalsteel': 'Blacks & Charcoal',
  'thermoshield1_charcoalgreystone': 'Blacks & Charcoal',
  'thermoshield1_charcoalgreywhite': 'Grays',
  'thermoshield1_charcoalwhite': 'Grays',
  'thermoshield1_cream': 'Grays',
  'thermoshield1_espresso': 'Blacks & Charcoal',
  'thermoshield1_mocha': 'Browns & Earth Tones',
  'thermoshield1_pearlcharcoal': 'Blacks & Charcoal',
  'thermoshield1_pearlcharcoalfawn': 'Browns & Earth Tones',
  'thermoshield1_pearlstonefawn': 'Browns & Earth Tones',
  'thermoshield1_toffee': 'Grays',
  'thermoshield1_whitecharcoal': 'Blacks & Charcoal',
  'thermoshield1_whitegrey': 'Grays',
  'thermoshield1_whitewhite': 'Whites',
  'thermoshield1_whitewhitesteel': 'Grays',
  'totalblock0p_alualu': 'Grays',
  'totalblock0p_aluminiumopaquealu': 'Grays',
  'totalblock0p_anthracite': 'Blacks & Charcoal',
  'totalblock0p_anthracitealu': 'Blacks & Charcoal',
  'totalblock0p_anthraciteopaquealu': 'Blacks & Charcoal',
  'totalblock0p_arenaalu': 'Reds & Oranges',
  'totalblock0p_blacksnowwhite': 'Blacks & Charcoal',
  'totalblock0p_blanclowe': 'Whites',
  'totalblock0p_clay': 'Beige & Natural Tones',
  'totalblock0p_clayalu': 'Beige & Natural Tones',
  'totalblock0p_clayopaquealu': 'Beige & Natural Tones',
  'totalblock0p_cranealu': 'Beige & Natural Tones',
  'totalblock0p_elephantalu': 'Grays',
  'totalblock0p_fjordalu': 'Grays',
  'totalblock0p_greenteaalu': 'Grays',
  'totalblock0p_hemp': 'Beige & Natural Tones',
  'totalblock0p_hempalu': 'Beige & Natural Tones',
  'totalblock0p_hempopaquealu': 'Beige & Natural Tones',
  'totalblock0p_lightgrey': 'Grays',
  'totalblock0p_lightgreyalu': 'Grays',
  'totalblock0p_lightgreyopaquealu': 'Grays',
  'totalblock0p_mediumgrey': 'Grays',
  'totalblock0p_mediumgreyalu': 'Grays',
  'totalblock0p_mediumgreyopaquealu': 'Grays',
  'totalblock0p_nashialu': 'Beige & Natural Tones',
  'totalblock0p_pinacoladaalu': 'Whites',
  'totalblock0p_quartz': 'Beige & Natural Tones',
  'totalblock0p_quartzalu': 'Beige & Natural Tones',
  'totalblock0p_quartzopaquealu': 'Beige & Natural Tones',
  'totalblock0p_sandybeige': 'Beige & Natural Tones',
  'totalblock0p_sandybeigealu': 'Beige & Natural Tones',
  'totalblock0p_showeralu': 'Blues',
  'totalblock0p_snowwhite': 'Whites',
  'totalblock0p_snowwhitealu': 'Whites',
  'totalblock0p_snowwhiteopaquealu': 'Whites',
  'totalblock0p_snowwhiteopaquewhite': 'Whites',
  'totalblock0p_spume': 'Whites',
  'totalblock0p_spumealu': 'Whites',
  'totalblock0p_spumeopaquealu': 'Whites',
  'totalblock0p_tahinialu': 'Yellows',
  'totalblock0p_thermalwateralu': 'Whites',
  'totalblock0p_white': 'Whites',
  'toughshade1p_whitebeige': 'Beige & Natural Tones',
  'toughshade1p_whitebronze': 'Beige & Natural Tones',
  'toughshade1p_whitecharcoal': 'Grays',
  'toughshade1p_whitedimgray': 'Grays',
  'toughshade1p_whitelightgray': 'Beige & Natural Tones',
  'toughshade1p_whitewhite': 'Whites',
  'tranquilhaven3p_baltic': 'Blues',
  'tranquilhaven3p_ceramic': 'Grays',
  'tranquilhaven3p_fossil': 'Blacks & Charcoal',
  'tranquilhaven3p_lava': 'Blacks & Charcoal',
  'tranquilhaven3p_limestone': 'Whites',
  'tranquilhaven3p_marble': 'Whites',
  'tranquilhaven3p_mineral': 'Whites',
  'tranquilhaven3p_plaster': 'Whites',
  'tranquilhaven3p_slate': 'Grays',
  'tranquilhaven3p_suede': 'Grays',
  'tranquilhaven3p_truffle': 'Grays',
  'ultrablock0p_ecru': 'Beige & Natural Tones',
  'ultrablock0p_eggshell': 'Beige & Natural Tones',
  'ultrablock0p_kohl': 'Blacks & Charcoal',
  'ultrablock0p_seal35': 'Browns & Earth Tones',
  'ultrablock0p_silver': 'Grays',
  'ultrablock0p_smoke': 'Grays',
  'ultrablock0p_snow': 'Whites',
  'ultrashield4_alu': 'Grays',
  'ultrashield4_alualu': 'Grays',
  'ultrashield4_aluanthracite': 'Grays',
  'ultrashield4_alumediumgrey': 'Grays',
  'ultrashield4_aluoat': 'Grays',
  'ultrashield4_aluwhite': 'Grays',
  'ultrashield4_aniseed': 'Yellows',
  'ultrashield4_anthracite': 'Blacks & Charcoal',
  'ultrashield4_beatenmetal': 'Grays',
  'ultrashield4_beetle': 'Greens',
  'ultrashield4_boulder': 'Grays',
  'ultrashield4_brick': 'Reds & Oranges',
  'ultrashield4_bronze': 'Blacks & Charcoal',
  'ultrashield4_buttercup': 'Yellows',
  'ultrashield4_celestialgrey': 'Blues',
  'ultrashield4_champagne': 'Beige & Natural Tones',
  'ultrashield4_cloud': 'Whites',
  'ultrashield4_concrete': 'Grays',
  'ultrashield4_copper': 'Reds & Oranges',
  'ultrashield4_darkgrey': 'Beige & Natural Tones',
  'ultrashield4_deepblack': 'Blacks & Charcoal',
  'ultrashield4_deepblue': 'Blues',
  'ultrashield4_deepred': 'Reds & Oranges',
  'ultrashield4_gold': 'Yellows',
  'ultrashield4_greengrey': 'Grays',
  'ultrashield4_havanabrown': 'Browns & Earth Tones',
  'ultrashield4_hemp': 'Beige & Natural Tones',
  'ultrashield4_lagoon': 'Blues',
  'ultrashield4_mossgreen': 'Greens',
  'ultrashield4_orange': 'Reds & Oranges',
  'ultrashield4_pepper': 'Yellows',
  'ultrashield4_quartz': 'Beige & Natural Tones',
  'ultrashield4_red': 'Reds & Oranges',
  'ultrashield4_sandybeige': 'Beige & Natural Tones',
  'ultrashield4_shea': 'Beige & Natural Tones',
  'ultrashield4_snowwhite': 'Whites',
  'ultrashield4_taupe': 'Beige & Natural Tones',
  'ultrashield4_tennisgreen': 'Greens',
  'ultrashield4_white': 'Whites',
  'urbanshade_blackblack': 'Blacks & Charcoal',
  'urbanshade_blackwhite': 'Blacks & Charcoal',
  'urbanshade_canvaswhite': 'Whites',
  'urbanshade_chalkwhite': 'Whites',
  'urbanshade_frostwhite': 'Grays',
  'urbanshade_graphitegraphite': 'Blacks & Charcoal',
  'urbanshade_graphitewhite': 'Blacks & Charcoal',
  'urbanshade_khakiwhite': 'Beige & Natural Tones',
  'urbanshade_linenwhite': 'Beige & Natural Tones',
  'urbanshade_pewterpewter': 'Grays',
  'urbanshade_pewterwhite': 'Grays',
  'urbanshade_whitewhite': 'Whites',
  'urbanview_birch': 'Whites',
  'urbanview_canvas': 'Beige & Natural Tones',
  'urbanview_canyon': 'Grays',
  'urbanview_cocoa': 'Browns & Earth Tones',
  'urbanview_graphite': 'Grays',
  'urbanview_merino': 'Beige & Natural Tones',
  'urbanview_mushroom': 'Beige & Natural Tones',
  'urbanview_onyx': 'Blacks & Charcoal',
  'urbanview_porpoise': 'Grays',
  'urbanview_sand': 'Beige & Natural Tones',
  'urbanview_wheat': 'Beige & Natural Tones',
  'urbanview_white': 'Whites',
  'vistashade5_charcoalbronze': 'Blacks & Charcoal',
  'vistashade5_charcoalcharcoal': 'Blacks & Charcoal',
  'vistashade5_charcoalgrey': 'Blacks & Charcoal',
  'vistashade5_charcoalsandbronze': 'Browns & Earth Tones',
  'vistashade5_charcoalwhitecharcoal': 'Blacks & Charcoal',
  'vistashade5_linenlinen': 'Beige & Natural Tones',
  'vistashade5_pearlgreylinen': 'Beige & Natural Tones',
  'vistashade5_pearlgreypearlgrey': 'Grays',
  'vistashade5_pearlgreysandbronze': 'Beige & Natural Tones',
  'vistashade5_pearlgreywhitecharcoal': 'Grays',
  'vistashade5_whitelinen': 'Beige & Natural Tones',
  'vistashade5_whitemandarine': 'Reds & Oranges',
  'vistashade5_whitepearlgrey': 'Beige & Natural Tones',
  'vistashade5_whitepistache': 'Greens',
  'vistashade5_whitesandbronze': 'Beige & Natural Tones',
  'vistashade5_whiteturquoise': 'Blues',
  'vistashade5_whitewhite': 'Whites',
  'vistashade5_whitewhitecharcoal': 'Grays',
  'vistashade5_whiteyellow': 'Yellows',
  'vistashade5_wowwhite': 'Whites',
  'vistaview5p_aluminium': 'Grays',
  'vistaview5p_anthracite': 'Blues',
  'vistaview5p_boulder': 'Whites',
  'vistaview5p_brick': 'Browns & Earth Tones',
  'vistaview5p_bronze': 'Browns & Earth Tones',
  'vistaview5p_celestialgrey': 'Blues',
  'vistaview5p_champagne': 'Beige & Natural Tones',
  'vistaview5p_concrete': 'Grays',
  'vistaview5p_darkgrey': 'Grays',
  'vistaview5p_deepblack': 'Blacks & Charcoal',
  'vistaview5p_greengrey': 'Grays',
  'vistaview5p_hemp': 'Beige & Natural Tones',
  'vistaview5p_offwhite': 'Beige & Natural Tones',
  'vistaview5p_pebblegrey': 'Grays',
  'vistaview5p_pepper': 'Reds & Oranges',
  'vistaview5p_sand': 'Beige & Natural Tones',
  'vistaview5p_sandybeige': 'Beige & Natural Tones',
  'vistaview5p_snowwhite': 'Whites',
  'vistaview5p_taupe': 'Grays',
  'vistaview5p_white': 'Whites',
  'vistaview5p_whitelowe': 'Whites',
  'vistaweave3p_beigebeige': 'Beige & Natural Tones',
  'vistaweave3p_beigegray': 'Beige & Natural Tones',
  'vistaweave3p_beigesable': 'Beige & Natural Tones',
  'vistaweave3p_charcoalbronze': 'Browns & Earth Tones',
  'vistaweave3p_charcoalcharcoal': 'Blacks & Charcoal',
  'vistaweave3p_charcoalgray': 'Beige & Natural Tones',
  'vistaweave3p_dovedove': 'Whites',
  'vistaweave3p_dovesand': 'Whites',
  'vistaweave3p_graydarkgray': 'Grays',
  'vistaweave3p_graygray': 'Grays',
  'vistaweave3p_whitebeige': 'Whites',
  'vistaweave3p_whitegray': 'Grays',
  'vistaweave3p_whitewhite': 'Whites',
  'zipguard5_cumulus': 'Beige & Natural Tones',
  'zipguard5_edelweiss': 'Beige & Natural Tones',
  'zipguard5_frostwhite': 'Beige & Natural Tones',
  'zipguard5_graphiteblack': 'Blacks & Charcoal',
  'zipguard5_greypepper': 'Blacks & Charcoal',
  'zipguard5_lunarsurface': 'Greens',
  'zipguard5_macadamia': 'Browns & Earth Tones',
  'zipguard5_mistral': 'Grays',
  'zipguard5_natural': 'Beige & Natural Tones',
  'zipguard5_sandalwood': 'Blacks & Charcoal',
  'zipguard5_sealion': 'Blacks & Charcoal',
  'zipguard5_seaurchin': 'Blacks & Charcoal',
  'zipguard5_shadow': 'Blacks & Charcoal',
  'zipguard5_tundra': 'Browns & Earth Tones',
  'zipguard5_volcano': 'Blacks & Charcoal',
};

export const getColorPill = (
  wwsFabricName: string,
  color: string
): ColorPill | null => {
  if (!wwsFabricName || !color) return null;
  const key = `${slugifyForPill(wwsFabricName)}_${slugifyForPill(color)}`;
  return FABRIC_COLOR_PILLS[key] ?? null;
};
